### ISSUE TITLE
Error when attempting to install ape-safe via pip install and ape plugin install

### ISSUE THREAD

**Issue by hhamud** [ApeWorX/ape-safe#20]
### Environment information

- `ape` and plugin versions:

```shell
(venv) user@Users-Laptop safe % ape --version
0.6.15
(venv) user@Users-Laptop safe % ape plugins list
No plugins installed. Use '--all' to see available plugins.
```

- Python Version: 3.10.12
- OS: OSX

### What went wrong?
Error when attempting to install ape-safe via pip install and ape plugin install

```shell
(venv) user@Users-Laptop safe % ape plugins install safe
INFO: Installing safe...
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef readonly object func
          cdef readonly tuple args
          cdef readonly dict keywords
          cdef public object __doc__
          cdef public object __name__
          cdef public object __module__
                             ^
      ------------------------------------------------------------
      
      cytoolz/functoolz.pxd:18:23: '__module__' redeclared
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef readonly object func
          cdef readonly tuple args
          cdef readonly dict keywords
          cdef public object __doc__
          cdef public object __name__
          cdef public object __module__
               ^
      ------------------------------------------------------------
      
      cytoolz/functoolz.pxd:18:9: Compiler crash in AnalyseDeclarationsTransform
      
      File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(functoolz.pxd:1:0,
          full_module_name = 'cytoolz.functoolz',
          is_pxd = True)
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:1:0)
      File 'Nodes.py', line 5497, in analyse_declarations: CClassDefNode(functoolz.pxd:10:5,
          as_name = 'curry',
          class_name = 'curry',
          in_pxd = True,
          module_name = '',
          punycode_class_name = 'curry',
          visibility = 'private')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:11:4)
      File 'Nodes.py', line 1528, in analyse_declarations: CVarDefNode(functoolz.pxd:18:9,
          in_pxd = True,
          modifiers = [...]/0,
          visibility = 'public')
      
      Compiler crash traceback from this point on:
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 1528, in analyse_declarations
          self.entry = dest_scope.declare_var(
                       ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 2389, in declare_var
          entry = self.declare(name, cname, type, pos, visibility)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 550, in declare
          entries[name].already_declared_here()
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 262, in already_declared_here
          error(self.pos, "Previous declaration is here")
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Compiler/Errors.py", line 178, in error
          raise InternalError(message)
      InternalError: Internal compiler error: Previous declaration is here
      [1/5] Cythonizing cytoolz/dicttoolz.pyx
      [2/5] Cythonizing cytoolz/functoolz.pyx
      Traceback (most recent call last):
        File "/Users/user/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 85, in <module>
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/3_/z8rn91w566l816hsprr2k4w80000gn/T/pip-build-env-e05_0hgb/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cytoolz/functoolz.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
ERROR: Failed to install plugin **'safe.**
### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by hhamud** [comment]
Solved via direct install from GitHub and not via the released versions
